### ISSUE TITLE
Minimal example server build fails due to non existing glsp server version

### ISSUE THREAD

**Issue by JonasHelming** [eclipse-glsp/glsp#178]
Points to 0.8.0 which is not published (anymore)

**Comment by JonasHelming** [comment]
When updating to 0.9.0, the build fails:

[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /workspace/glsp-examples/minimal/server/org.eclipse.glsp.example.minimal/src/main/java/org/eclipse/glsp/example/minimal/MinimalGLSPModule.java:[21,51] cannot find symbol
  symbol:   class JsonFileModelFactory
  location: package org.eclipse.glsp.server.features.core.model
[ERROR] /workspace/glsp-examples/minimal/server/org.eclipse.glsp.example.minimal/src/main/java/org/eclipse/glsp/example/minimal/MinimalGLSPModule.java:[22,51] cannot find symbol
  symbol:   class ModelFactory
  location: package org.eclipse.glsp.server.features.core.model
[ERROR] /workspace/glsp-examples/minimal/server/org.eclipse.glsp.example.minimal/src/main/java/org/eclipse/glsp/example/minimal/MinimalGLSPModule.java:[40,30] cannot find symbol
  symbol:   class ModelFactory
  location: class org.eclipse.glsp.example.minimal.MinimalGLSPModule
[ERROR] /workspace/glsp-examples/minimal/server/org.eclipse.glsp.example.minimal/src/main/java/org/eclipse/glsp/example/minimal/MinimalGLSPModule.java:[26,8] org.eclipse.glsp.example.minimal.MinimalGLSPModule is not abstract and does not override abstract method bindGModelFactory() in org.eclipse.glsp.server.di.GLSPModule
[ERROR] /workspace/glsp-examples/minimal/server/org.eclipse.glsp.example.minimal/src/main/java/org/eclipse/glsp/example/minimal/MinimalGLSPModule.java:[39,4] method does not override or implement a method from a supertype
[ERROR] /workspace/glsp-examples/minimal/server/org.eclipse.glsp.example.minimal/src/main/java/org/eclipse/glsp/example/minimal/MinimalGLSPModule.java:[41,14] cannot find symbol
  symbol:   class JsonFileModelFactory
  location: class org.eclipse.glsp.example.minimal.MinimalGLSPModule
[INFO] 6 errors

**Comment by JonasHelming** [comment]
I think testing these examples should also be part of the release process if not already (@planger )

**Comment by planger** [comment]
Yes, 0.9.0 is not released yet so the minimal example hasn't been migrated yet. I added the check to the process. Thus, this will be done on 0.9.0 release.
